version: "3.3"
services:
  angular-docker:
    container_name: angular-docker-container
    build: ./frontend/supermarket-frontend
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
